name: 'Sync `staging` Branch'

# This workflow attempts to merge updates from `master` into the long-standing staging branch.

on:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency: merge_master

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Merge `master` branch
        uses: everlytic/branch-merge@1.1.2 # TSCCR: no entry for repository "everlytic/branch-merge"
        id: branch-merge
        with:
          github_token: ${{  secrets.GITHUB_TOKEN }}
          source_ref: 'master'
          target_branch: 'staging'
          commit_message_template: '[Automated] Merged {source_ref} into target: {target_branch}'
